version:                2
jobs:
  build:
    docker:
      - image:          docker:18-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name:         Login to Docker registry
          command:      echo $ARTIFACTORY_TOKEN | docker login --username "$ARTIFACTORY_USER" --password-stdin fundingcircle-docker-registry.jfrog.io
      - run:
          name:         Build
          command:      docker build . --tag `echo "$ARTIFACTORY_DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME"| tr '[:upper:]' '[:lower:]'`:latest
      - run:
          name:         Push
          command:      docker push `echo "$ARTIFACTORY_DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME"| tr '[:upper:]' '[:lower:]'`:latest

workflows:
  version:              2
  build-and-push-image:
    jobs:
      - build:
          context:      org-global
